import 'package:get/get.dart';

@override
class Language extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          "Nurse visit": "Nurse visit",
          "Doctor visit": "Doctor visit",
          "Virtual consultation": "Virtual consultation",
          "Vitamin IV drips and fluids": "Vitamin IV drips and fluids",
          "Laboratory": "Laboratory",
          "Our Services ": "Our Services ",
          "Appointments" : "Appointments",
          "Accepted appointments": "Accepted appointments",
          "Contact": "Contact",
          "Family" : "Family",
          "About us": "About us",
          "Your requests": "Your requests",
          "logout": "Logout",
          "Login" : "Login",
          "Register": "Register",
          "Result upload": "Result Upload",
          "Upload Result": "Upload Result",
          "Name": "Name",
          "email": "email",
          "phone number": "phone number" ,
          "password": "password",
          "Register as a Service Provider": "Register as a Service Provider",
          "Designation": "Designation",
          "Register as a User": "Register as a User",
          "30% Discount for the first order": "30% Discount for the first order",
          "Please Select Your Designation": "Please Select Your Designation",
          "Harees": "Harees",
          "Your Account": "Your Account",
          "Settings": "Settings",
          "Logout": "Logout",
          "Completed Requests:": "Completed Requests:",
          "Search...": "Search...",
          "See result": "See result",
          "Something went wrong": "Something went wrong",
          "Loading": "Loading",
          "Accept Appointment": "Accept Appointment",
          "Are you sure?": "Are you sure?",
          "Yes": "Yes",
          "No": "No",
          "Joining as a Service Provider": "Joining as a Service Provider",
          "Name required": "Name required",
          "Email required": "Email required",
          "Password required": "Password required",
          "ID CARD Number": "ID CARD Number",
          "ID Number required": "ID Number required",
          "Email cannot be empty": "Email cannot be empty",
          "Password cannot be empty": "Password cannot be empty",
          "Not a provider?": "Not a provider?",
          "Register Now": "Register Now",
          "Upload Result here": "Upload Result here",
          "Success": "Success",
          "Appointment Accepted check your accepted appointments": "Appointment Accepted check your accepted appointments",
          "Service Type: Laboratory": "Service Type: Laboratory",
          "Service Type: Doctor Visit": "Service Type: Doctor Visit",
          "Service Type: Nurse Visit": "Service Type: Nurse Visit",
          "Join as a provider": "Join as a provider",
          "Join as a user": "Join as a user",
          "Contact Us": "Contact Us",
          "Enter your message": "Enter your message",
          "Submit": "Submit",
          "Services:": "Services:",
          "Your accepted requests:": "Your accepted requests:",
          "Service Type: Virtual Consultation": "Service Type: Virtual Consultation",
          "Service Type: Vitamin IV Drips And Fluids": "Service Type: Vitamin IV Drips And Fluids",
          "Not a member?": "Not a member?",
          "Account created successfully": "Account created successfully",
          "The email address is already in use by another account.": "The email address is already in use by another account.",
          "The password provided is too weak.": "The password provided is too weak.",
          "An error occurred while creating the account.": "An error occurred while creating the account.",
          "Error": "Error",
          "Already a member?": "Already a member?",
          "Let's login": "Let's login",
          "Current Location": "Current Location",
          "My Location": "My Location",
          "To proceed": "To proceed",
          "Kindly click on your address mentioned below": "Kindly click on your address mentioned below",
          "Are you sure you want to confirm": "Are you sure you want to confirm",
          "Confirm": "Confirm",
          "Cancel": "Cancel",
          "Address will appear here when you press the button": "Address will appear here when you press the button",
          "Our Services:": "Our Services:",
          "Other Services:": "Other Services:",
          "Pending appointments": "Pending appointments",
          "Your result": "Your result",
          "Upload Results": "Upload Results",

        },

        "ar_AE": {

          "Nurse visit": "زيارة تمريض",
          "Doctor visit": "زيارة طبيب",
          "Virtual consultation": "استشارة طبيب عن بعد",
          "Laboratory": " الفحوصات",
          "Vitamin IV drips and fluids": "المحاليل والسوائل",
          "Our Services ": " خدماتنا ",
          "Appointments": "المواعيد",
          "Accepted appointments": "المواعيد المقبولة",
          "Contact": "اتصل بنا",
          "Family": "عائلة",
          "About us": "من نحن",
          "Your requests": "طلباتك",
          "logout": "تسجيل خروج",
          "Login": "تسجيل الدخول",
          "Register": "تسجيل",
          "Result upload": "تحميل نتيجة",
          "Upload Result": "تحميل نتيجة",
          "Name": "الاسم",
          "email": "البريد الالكتروني",
          "phone number": "رقم الهاتف",
          "password": "كلمة المرور",
          "Register as a Service Provider": "تسجيل كمزود خدمة",
          "Designation": "التعيين",
          "Register as a User": "تسجيل كمستخدم",
          "30% Discount for the first order": "خصم 30٪ على الطلب الأول",
          "Please Select Your Designation": "الرجاء تحديد التعيين الخاص بك",
          "Harees": "حاريس",
          "Your Account": "الحساب الخاص بك",
          "Settings": "إعدادات",
          "Logout": "تسجيل خروج",
          "Completed Requests:": "الطلبات المكتملة:",
          "Search...": "ابحث...",
          "See result": "انظر النتيجة ",
          "Something went wrong": "هناك خطأ ما",
          "Loading": "تحميل",
          "Accept Appointment": "قبول الموعد",
          "Are you sure?": "هل انت متأكد؟",
          "Yes": "نعم",
          "No": "لا",
          "Joining as a Service Provider": "الانضمام كمقدم خدمة",
          "Name required": "الاسم مطلوب",
          "Email required": "البريد الالكتروني مطلوب",
          "Password required": "كلمة المرور مطلوبة",
          "ID CARD Number": "رقم بطاقة الهوية",
          "ID Number required": "رقم الهوية مطلوب",
          "Email cannot be empty": "لا يمكن ترك البريد الالكتروني فارغ",
          "Password cannot be empty": "لا يمكن ترك كلمة المرور فارغة",
          "Not a provider?": "ليس مزود؟",
          "Register Now": "سجل الان",
          "Upload Result here": "تحميل نتيجتك هنا",
          "Success": "نجاح",
          "Appointment Accepted check your accepted appointments": "تم قبول الموعد الرجاء التحقق من مواعيدك المقبولة",
          "Service Type: Laboratory": "نوع الخدمة: مختبر",
          "Service Type: Doctor Visit": "نوع الخدمة: زيارة طبيب",
          "Service Type: Nurse Visit": "نوع الخدمة: زيارة ممرض",
          "Join as a provider": "انضم كمزود",
          "Join as a user": "انضم كمستخدم",
          "Contact Us": "اتصل بنا",
          "Enter your message": "ادخل رسالتك",
          "Submit": "ارسال",
          "Services:": "الخدمات:",
          "Your accepted requests:": "طلباتك المقبولة:",
          "Service Type: Virtual Consultation": "نوع الخدمة: استشارة فعالة",
          "Service Type: Vitamin IV Drips And Fluids": "نوع الخدمة: نقط وسوائل فيتامين الرابع",
          "Not a member?": "ليس عضو؟",
          "Account created successfully": "الحساب اقيم بنجاح",
          "The email address is already in use by another account.": "عنوان البريد الإلكتروني قيد الاستخدام بالفعل من قبل حساب آخر.",
          "The password provided is too weak.": "كلمة المرور المقدمة ضعيفة جدًا.",
          "An error occurred while creating the account.": "حدث خطأ اثناء انشاء الحساب.",
          "Error": "خطأ",
          "Already a member?": "عضوا فعلا؟",
          "Let's login": "دعونا تسجيل الدخول",
          "Current Location": "موقعك الحالي",
          "My Location": "موقعي",
          "To proceed": "للمتابعة",
          "Kindly click on your address mentioned below": "يرجى النقر على العنوان المذكورة ادناه",
          "Are you sure you want to confirm": "هل انت متأكد من تأكيد",
          "Confirm": "تأكيد",
          "Cancel": "الغاء",
          "Address will appear here when you press the button": "سيظهر العنوان هنا عند الضغط على الزر",
          "Our Services:": "خدماتنا:",
          "Other Services:": "خدمات اخرى:",
          "Pending appointments": "مواعيد معلقة",
          "Your result": "نتيجتك",
          "Upload Results": "تحميل نتيجتك",

        }
      };
}
